docs(blevm): README (#95)
Closes https://github.com/celestiaorg/celestia-zkevm-ibc-demo/issues/92
but will need to add to it.

This PR includes steps for contributors to run the blevm script. Note,
the script currently fails to generate a proof while using the SP1
prover network:

```shell
commitment from test vector: 7946cf528edd745efb25201246e647d5aaca3fb52bf0f606b695b4ab0bd33f4c
stdout: WARNING: Using insecure random number generator.
stdout: 7946cf528edd745efb25201246e647d5aaca3fb52bf0f606b695b4ab0bd33f4c

thread 'main' panicked at script/src/bin/main.rs:215:55:
called `Result::unwrap()` on an `Err` value: Proof generation failed: Unexpected prover error
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

It also looks like the script generates a proof that some blob is in a
particular Celestia block when I thought this service would have
generated a proof of some EVM state transition